### ISSUE TITLE
Bug: Tag loading fails when file name contains closing parenthesis )

### ISSUE THREAD

**Issue by Miyuutsu** [derrian-distro/BooruTagEditorUI#1]
When loading a directory that contains files with a closing parenthesis `)` in their file name, it fails to load that image and its tags. 

Working: image1.png
Working: image(1.png
Fail: image(1).png

Position of closing parenthesis does not seem to matter.

**Comment by derrian-distro** [comment]
Commit [4415f6d](https://github.com/derrian-distro/BooruTagEditorUI/commit/4415f6d28cd3c6c640e4b3b7004bc6ad02d1ec71) *should* fix your issue
